<a href="https://colab.research.google.com/github/mrafiasyifaa/Belajar-Mandiri/blob/main/20250507_00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

# Create random tensor
tensor=torch.rand(size=(7,7))
tensor

tensor([[0.6128, 0.3311, 0.6762, 0.7668, 0.6669, 0.5279, 0.3165],
        [0.3602, 0.6515, 0.4509, 0.2703, 0.1490, 0.9176, 0.5544],
        [0.2815, 0.7361, 0.1149, 0.9480, 0.7667, 0.9355, 0.7394],
        [0.6366, 0.7835, 0.0863, 0.4691, 0.8023, 0.5495, 0.9037],
        [0.0384, 0.4360, 0.5886, 0.1987, 0.6012, 0.7079, 0.5132],
        [0.6432, 0.8003, 0.4098, 0.3374, 0.3156, 0.4617, 0.0560],
        [0.6229, 0.6514, 0.5309, 0.3608, 0.8520, 0.4770, 0.4925]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
tensor2=torch.rand(size=(1,7))
# Perform matrix multiplication
torch.matmul(tensor,tensor2.T)

tensor([[2.6409],
        [2.5979],
        [3.5823],
        [3.2251],
        [2.3184],
        [2.1543],
        [2.8075]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [12]:
import random
# Set manual seed
R_SEED=0
torch.manual_seed(seed=R_SEED)

# Create two random tensors
random_tensorA=torch.rand(7,7)
random_tensorB=torch.rand(1,7)
# Matrix multiply tensors
torch.matmul(random_tensorA, random_tensorB.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [14]:
# Set random seed on the GPU
# Check for GPU

torch.cuda.is_available()
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [18]:
# Set random seed
R2_SEED=1234
torch.manual_seed(R2_SEED)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
random_tensorA=torch.rand(2,3).to(device)
random_tensorB=torch.rand(2,3).to(device)
random_tensorA, random_tensorB

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [22]:
# Perform matmul on tensor_A and tensor_B
tensor7=torch.matmul(random_tensorA, random_tensorB.T)
tensor7

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [23]:
# Find max
print(f"Max: {tensor7.max()}")
# Find min
print(f"Min: {tensor7.min()}")

Max: 0.5617256760597229
Min: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [24]:
# Find arg max
print(f"Maximum value is in {tensor7.argmax()} index")

# Find arg min
print(f"Maximum value is in {tensor7.argmin()} index")

Maximum value is in 3 index
Maximum value is in 0 index



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [27]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensorFinalA = torch.rand(size=(1,1,1,10))


# Remove single dimensions
tensorFinalB = tensorFinalA.squeeze()

# Print out tensors and their shapes
print(tensorFinalA, tensorFinalA.shape)
print(tensorFinalB, tensorFinalB.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
